'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Messages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SilverlightDataEntry.Messages", GetType(Messages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must provide an Address Line 1..
        '''</summary>
        Friend Shared ReadOnly Property BlankAddressLine1() As String
            Get
                Return ResourceManager.GetString("BlankAddressLine1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The current appointment type is .
        '''</summary>
        Friend Shared ReadOnly Property CurrentAppointmentType() As String
            Get
                Return ResourceManager.GetString("CurrentAppointmentType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consumer Address &apos;{0}&apos; has not been saved.  Do you want to save before closing?.
        '''</summary>
        Friend Shared ReadOnly Property DirtyConsumerAddressOnClose() As String
            Get
                Return ResourceManager.GetString("DirtyConsumerAddressOnClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consumer &apos;{0}&apos; has not been saved.  Do you want to save before closing?.
        '''</summary>
        Friend Shared ReadOnly Property DirtyConsumerOnClose() As String
            Get
                Return ResourceManager.GetString("DirtyConsumerOnClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to , First Name - .
        '''</summary>
        Friend Shared ReadOnly Property FirstName() As String
            Get
                Return ResourceManager.GetString("FirstName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consumer Address &apos;{0}&apos; is invalid.  Changes will be lost.  Do you still want to close?.
        '''</summary>
        Friend Shared ReadOnly Property InvalidConsumerAddressOnClose() As String
            Get
                Return ResourceManager.GetString("InvalidConsumerAddressOnClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consumer &apos;{0}&apos; is invalid.  Changes will be lost.  Do you still want to close?.
        '''</summary>
        Friend Shared ReadOnly Property InvalidConsumerOnClose() As String
            Get
                Return ResourceManager.GetString("InvalidConsumerOnClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to , Last Name - .
        '''</summary>
        Friend Shared ReadOnly Property LastName() As String
            Get
                Return ResourceManager.GetString("LastName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Entered .
        '''</summary>
        Friend Shared ReadOnly Property NotEntered() As String
            Get
                Return ResourceManager.GetString("NotEntered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The search parameters are Account Number - .
        '''</summary>
        Friend Shared ReadOnly Property SearchParametersAre() As String
            Get
                Return ResourceManager.GetString("SearchParametersAre", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
