'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

'
'This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
'
Namespace SearchService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ServiceSearchResults", [Namespace]:="http://schemas.datacontract.org/2004/07/SilverlightDataEntry.Service")>  _
    Partial Public Class ServiceSearchResults
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private Service_AccountNumberField As String
        
        Private Service_CustomerAccountStatusField As SearchService.AccountStatus
        
        Private Service_DateCreatedField As Date
        
        Private Service_DateOfBirthField As String
        
        Private Service_FirstNameField As String
        
        Private Service_IdField As System.Guid
        
        Private Service_LastNameField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_AccountNumber() As String
            Get
                Return Me.Service_AccountNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Service_AccountNumberField, value) <> true) Then
                    Me.Service_AccountNumberField = value
                    Me.RaisePropertyChanged("Service_AccountNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_CustomerAccountStatus() As SearchService.AccountStatus
            Get
                Return Me.Service_CustomerAccountStatusField
            End Get
            Set
                If (Me.Service_CustomerAccountStatusField.Equals(value) <> true) Then
                    Me.Service_CustomerAccountStatusField = value
                    Me.RaisePropertyChanged("Service_CustomerAccountStatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_DateCreated() As Date
            Get
                Return Me.Service_DateCreatedField
            End Get
            Set
                If (Me.Service_DateCreatedField.Equals(value) <> true) Then
                    Me.Service_DateCreatedField = value
                    Me.RaisePropertyChanged("Service_DateCreated")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_DateOfBirth() As String
            Get
                Return Me.Service_DateOfBirthField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Service_DateOfBirthField, value) <> true) Then
                    Me.Service_DateOfBirthField = value
                    Me.RaisePropertyChanged("Service_DateOfBirth")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_FirstName() As String
            Get
                Return Me.Service_FirstNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Service_FirstNameField, value) <> true) Then
                    Me.Service_FirstNameField = value
                    Me.RaisePropertyChanged("Service_FirstName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_Id() As System.Guid
            Get
                Return Me.Service_IdField
            End Get
            Set
                If (Me.Service_IdField.Equals(value) <> true) Then
                    Me.Service_IdField = value
                    Me.RaisePropertyChanged("Service_Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_LastName() As String
            Get
                Return Me.Service_LastNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Service_LastNameField, value) <> true) Then
                    Me.Service_LastNameField = value
                    Me.RaisePropertyChanged("Service_LastName")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AccountStatus", [Namespace]:="http://schemas.datacontract.org/2004/07/SilverlightDataEntry.Service")>  _
    Public Enum AccountStatus As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Failure = -10
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Warning = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Good = 10
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ServiceConsumer", [Namespace]:="http://schemas.datacontract.org/2004/07/SilverlightDataEntry.Service")>  _
    Partial Public Class ServiceConsumer
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private Service_AccountNumberField As String
        
        Private Service_AmountOwedField As Double
        
        Private Service_CustomerAccountStatusField As SearchService.AccountStatus
        
        Private Service_CustomerLevelField As String
        
        Private Service_DateCreatedField As Date
        
        Private Service_DateOfBirthField As String
        
        Private Service_FirstNameField As String
        
        Private Service_IdField As System.Guid
        
        Private Service_LastNameField As String
        
        Private Service_OrderCountField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_AccountNumber() As String
            Get
                Return Me.Service_AccountNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Service_AccountNumberField, value) <> true) Then
                    Me.Service_AccountNumberField = value
                    Me.RaisePropertyChanged("Service_AccountNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_AmountOwed() As Double
            Get
                Return Me.Service_AmountOwedField
            End Get
            Set
                If (Me.Service_AmountOwedField.Equals(value) <> true) Then
                    Me.Service_AmountOwedField = value
                    Me.RaisePropertyChanged("Service_AmountOwed")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_CustomerAccountStatus() As SearchService.AccountStatus
            Get
                Return Me.Service_CustomerAccountStatusField
            End Get
            Set
                If (Me.Service_CustomerAccountStatusField.Equals(value) <> true) Then
                    Me.Service_CustomerAccountStatusField = value
                    Me.RaisePropertyChanged("Service_CustomerAccountStatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_CustomerLevel() As String
            Get
                Return Me.Service_CustomerLevelField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Service_CustomerLevelField, value) <> true) Then
                    Me.Service_CustomerLevelField = value
                    Me.RaisePropertyChanged("Service_CustomerLevel")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_DateCreated() As Date
            Get
                Return Me.Service_DateCreatedField
            End Get
            Set
                If (Me.Service_DateCreatedField.Equals(value) <> true) Then
                    Me.Service_DateCreatedField = value
                    Me.RaisePropertyChanged("Service_DateCreated")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_DateOfBirth() As String
            Get
                Return Me.Service_DateOfBirthField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Service_DateOfBirthField, value) <> true) Then
                    Me.Service_DateOfBirthField = value
                    Me.RaisePropertyChanged("Service_DateOfBirth")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_FirstName() As String
            Get
                Return Me.Service_FirstNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Service_FirstNameField, value) <> true) Then
                    Me.Service_FirstNameField = value
                    Me.RaisePropertyChanged("Service_FirstName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_Id() As System.Guid
            Get
                Return Me.Service_IdField
            End Get
            Set
                If (Me.Service_IdField.Equals(value) <> true) Then
                    Me.Service_IdField = value
                    Me.RaisePropertyChanged("Service_Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_LastName() As String
            Get
                Return Me.Service_LastNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Service_LastNameField, value) <> true) Then
                    Me.Service_LastNameField = value
                    Me.RaisePropertyChanged("Service_LastName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_OrderCount() As Integer
            Get
                Return Me.Service_OrderCountField
            End Get
            Set
                If (Me.Service_OrderCountField.Equals(value) <> true) Then
                    Me.Service_OrderCountField = value
                    Me.RaisePropertyChanged("Service_OrderCount")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ServiceConsumerAdress", [Namespace]:="http://schemas.datacontract.org/2004/07/SilverlightDataEntry.Service")>  _
    Partial Public Class ServiceConsumerAdress
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private Service_AccountNumberField As String
        
        Private Service_Address1Field As String
        
        Private Service_Address2Field As String
        
        Private Service_CityField As String
        
        Private Service_FirstNameField As String
        
        Private Service_IdField As System.Guid
        
        Private Service_LastNameField As String
        
        Private Service_StateField As String
        
        Private Service_ZipField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_AccountNumber() As String
            Get
                Return Me.Service_AccountNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Service_AccountNumberField, value) <> true) Then
                    Me.Service_AccountNumberField = value
                    Me.RaisePropertyChanged("Service_AccountNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_Address1() As String
            Get
                Return Me.Service_Address1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Service_Address1Field, value) <> true) Then
                    Me.Service_Address1Field = value
                    Me.RaisePropertyChanged("Service_Address1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_Address2() As String
            Get
                Return Me.Service_Address2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Service_Address2Field, value) <> true) Then
                    Me.Service_Address2Field = value
                    Me.RaisePropertyChanged("Service_Address2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_City() As String
            Get
                Return Me.Service_CityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Service_CityField, value) <> true) Then
                    Me.Service_CityField = value
                    Me.RaisePropertyChanged("Service_City")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_FirstName() As String
            Get
                Return Me.Service_FirstNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Service_FirstNameField, value) <> true) Then
                    Me.Service_FirstNameField = value
                    Me.RaisePropertyChanged("Service_FirstName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_Id() As System.Guid
            Get
                Return Me.Service_IdField
            End Get
            Set
                If (Me.Service_IdField.Equals(value) <> true) Then
                    Me.Service_IdField = value
                    Me.RaisePropertyChanged("Service_Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_LastName() As String
            Get
                Return Me.Service_LastNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Service_LastNameField, value) <> true) Then
                    Me.Service_LastNameField = value
                    Me.RaisePropertyChanged("Service_LastName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_State() As String
            Get
                Return Me.Service_StateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Service_StateField, value) <> true) Then
                    Me.Service_StateField = value
                    Me.RaisePropertyChanged("Service_State")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service_Zip() As String
            Get
                Return Me.Service_ZipField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Service_ZipField, value) <> true) Then
                    Me.Service_ZipField = value
                    Me.RaisePropertyChanged("Service_Zip")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SearchService.ISearchData")>  _
    Public Interface ISearchData
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ISearchData/GetSearchData", ReplyAction:="http://tempuri.org/ISearchData/GetSearchDataResponse")>  _
        Function BeginGetSearchData(ByVal accountNumber As String, ByVal firstName As String, ByVal lastName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGetSearchData(ByVal result As System.IAsyncResult) As System.Collections.ObjectModel.ObservableCollection(Of SearchService.ServiceSearchResults)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ISearchData/UpdateConsumer", ReplyAction:="http://tempuri.org/ISearchData/UpdateConsumerResponse")>  _
        Function BeginUpdateConsumer(ByVal item As SearchService.ServiceConsumer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndUpdateConsumer(ByVal result As System.IAsyncResult)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ISearchData/UpdateConsumerAddress", ReplyAction:="http://tempuri.org/ISearchData/UpdateConsumerAddressResponse")>  _
        Function BeginUpdateConsumerAddress(ByVal item As SearchService.ServiceConsumerAdress, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndUpdateConsumerAddress(ByVal result As System.IAsyncResult)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISearchDataChannel
        Inherits SearchService.ISearchData, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GetSearchDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As System.Collections.ObjectModel.ObservableCollection(Of SearchService.ServiceSearchResults)
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Collections.ObjectModel.ObservableCollection(Of SearchService.ServiceSearchResults))
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SearchDataClient
        Inherits System.ServiceModel.ClientBase(Of SearchService.ISearchData)
        Implements SearchService.ISearchData
        
        Private onBeginGetSearchDataDelegate As BeginOperationDelegate
        
        Private onEndGetSearchDataDelegate As EndOperationDelegate
        
        Private onGetSearchDataCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginUpdateConsumerDelegate As BeginOperationDelegate
        
        Private onEndUpdateConsumerDelegate As EndOperationDelegate
        
        Private onUpdateConsumerCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginUpdateConsumerAddressDelegate As BeginOperationDelegate
        
        Private onEndUpdateConsumerAddressDelegate As EndOperationDelegate
        
        Private onUpdateConsumerAddressCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginOpenDelegate As BeginOperationDelegate
        
        Private onEndOpenDelegate As EndOperationDelegate
        
        Private onOpenCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginCloseDelegate As BeginOperationDelegate
        
        Private onEndCloseDelegate As EndOperationDelegate
        
        Private onCloseCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Property CookieContainer() As System.Net.CookieContainer
            Get
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    Return httpCookieContainerManager.CookieContainer
                Else
                    Return Nothing
                End If
            End Get
            Set
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    httpCookieContainerManager.CookieContainer = value
                Else
                    Throw New System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC"& _ 
                            "ookieContainerBindingElement.")
                End If
            End Set
        End Property
        
        Public Event GetSearchDataCompleted As System.EventHandler(Of GetSearchDataCompletedEventArgs)
        
        Public Event UpdateConsumerCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event UpdateConsumerAddressCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event OpenCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event CloseCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SearchService_ISearchData_BeginGetSearchData(ByVal accountNumber As String, ByVal firstName As String, ByVal lastName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements SearchService.ISearchData.BeginGetSearchData
            Return MyBase.Channel.BeginGetSearchData(accountNumber, firstName, lastName, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SearchService_ISearchData_EndGetSearchData(ByVal result As System.IAsyncResult) As System.Collections.ObjectModel.ObservableCollection(Of SearchService.ServiceSearchResults) Implements SearchService.ISearchData.EndGetSearchData
            Return MyBase.Channel.EndGetSearchData(result)
        End Function
        
        Private Function OnBeginGetSearchData(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim accountNumber As String = CType(inValues(0),String)
            Dim firstName As String = CType(inValues(1),String)
            Dim lastName As String = CType(inValues(2),String)
            Return CType(Me,SearchService.ISearchData).BeginGetSearchData(accountNumber, firstName, lastName, callback, asyncState)
        End Function
        
        Private Function OnEndGetSearchData(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As System.Collections.ObjectModel.ObservableCollection(Of SearchService.ServiceSearchResults) = CType(Me,SearchService.ISearchData).EndGetSearchData(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnGetSearchDataCompleted(ByVal state As Object)
            If (Not (Me.GetSearchDataCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent GetSearchDataCompleted(Me, New GetSearchDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub GetSearchDataAsync(ByVal accountNumber As String, ByVal firstName As String, ByVal lastName As String)
            Me.GetSearchDataAsync(accountNumber, firstName, lastName, Nothing)
        End Sub
        
        Public Overloads Sub GetSearchDataAsync(ByVal accountNumber As String, ByVal firstName As String, ByVal lastName As String, ByVal userState As Object)
            If (Me.onBeginGetSearchDataDelegate Is Nothing) Then
                Me.onBeginGetSearchDataDelegate = AddressOf Me.OnBeginGetSearchData
            End If
            If (Me.onEndGetSearchDataDelegate Is Nothing) Then
                Me.onEndGetSearchDataDelegate = AddressOf Me.OnEndGetSearchData
            End If
            If (Me.onGetSearchDataCompletedDelegate Is Nothing) Then
                Me.onGetSearchDataCompletedDelegate = AddressOf Me.OnGetSearchDataCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginGetSearchDataDelegate, New Object() {accountNumber, firstName, lastName}, Me.onEndGetSearchDataDelegate, Me.onGetSearchDataCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SearchService_ISearchData_BeginUpdateConsumer(ByVal item As SearchService.ServiceConsumer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements SearchService.ISearchData.BeginUpdateConsumer
            Return MyBase.Channel.BeginUpdateConsumer(item, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Sub SearchService_ISearchData_EndUpdateConsumer(ByVal result As System.IAsyncResult) Implements SearchService.ISearchData.EndUpdateConsumer
            MyBase.Channel.EndUpdateConsumer(result)
        End Sub
        
        Private Function OnBeginUpdateConsumer(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim item As SearchService.ServiceConsumer = CType(inValues(0),SearchService.ServiceConsumer)
            Return CType(Me,SearchService.ISearchData).BeginUpdateConsumer(item, callback, asyncState)
        End Function
        
        Private Function OnEndUpdateConsumer(ByVal result As System.IAsyncResult) As Object()
            CType(Me,SearchService.ISearchData).EndUpdateConsumer(result)
            Return Nothing
        End Function
        
        Private Sub OnUpdateConsumerCompleted(ByVal state As Object)
            If (Not (Me.UpdateConsumerCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent UpdateConsumerCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub UpdateConsumerAsync(ByVal item As SearchService.ServiceConsumer)
            Me.UpdateConsumerAsync(item, Nothing)
        End Sub
        
        Public Overloads Sub UpdateConsumerAsync(ByVal item As SearchService.ServiceConsumer, ByVal userState As Object)
            If (Me.onBeginUpdateConsumerDelegate Is Nothing) Then
                Me.onBeginUpdateConsumerDelegate = AddressOf Me.OnBeginUpdateConsumer
            End If
            If (Me.onEndUpdateConsumerDelegate Is Nothing) Then
                Me.onEndUpdateConsumerDelegate = AddressOf Me.OnEndUpdateConsumer
            End If
            If (Me.onUpdateConsumerCompletedDelegate Is Nothing) Then
                Me.onUpdateConsumerCompletedDelegate = AddressOf Me.OnUpdateConsumerCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginUpdateConsumerDelegate, New Object() {item}, Me.onEndUpdateConsumerDelegate, Me.onUpdateConsumerCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SearchService_ISearchData_BeginUpdateConsumerAddress(ByVal item As SearchService.ServiceConsumerAdress, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements SearchService.ISearchData.BeginUpdateConsumerAddress
            Return MyBase.Channel.BeginUpdateConsumerAddress(item, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Sub SearchService_ISearchData_EndUpdateConsumerAddress(ByVal result As System.IAsyncResult) Implements SearchService.ISearchData.EndUpdateConsumerAddress
            MyBase.Channel.EndUpdateConsumerAddress(result)
        End Sub
        
        Private Function OnBeginUpdateConsumerAddress(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim item As SearchService.ServiceConsumerAdress = CType(inValues(0),SearchService.ServiceConsumerAdress)
            Return CType(Me,SearchService.ISearchData).BeginUpdateConsumerAddress(item, callback, asyncState)
        End Function
        
        Private Function OnEndUpdateConsumerAddress(ByVal result As System.IAsyncResult) As Object()
            CType(Me,SearchService.ISearchData).EndUpdateConsumerAddress(result)
            Return Nothing
        End Function
        
        Private Sub OnUpdateConsumerAddressCompleted(ByVal state As Object)
            If (Not (Me.UpdateConsumerAddressCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent UpdateConsumerAddressCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub UpdateConsumerAddressAsync(ByVal item As SearchService.ServiceConsumerAdress)
            Me.UpdateConsumerAddressAsync(item, Nothing)
        End Sub
        
        Public Overloads Sub UpdateConsumerAddressAsync(ByVal item As SearchService.ServiceConsumerAdress, ByVal userState As Object)
            If (Me.onBeginUpdateConsumerAddressDelegate Is Nothing) Then
                Me.onBeginUpdateConsumerAddressDelegate = AddressOf Me.OnBeginUpdateConsumerAddress
            End If
            If (Me.onEndUpdateConsumerAddressDelegate Is Nothing) Then
                Me.onEndUpdateConsumerAddressDelegate = AddressOf Me.OnEndUpdateConsumerAddress
            End If
            If (Me.onUpdateConsumerAddressCompletedDelegate Is Nothing) Then
                Me.onUpdateConsumerAddressCompletedDelegate = AddressOf Me.OnUpdateConsumerAddressCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginUpdateConsumerAddressDelegate, New Object() {item}, Me.onEndUpdateConsumerAddressDelegate, Me.onUpdateConsumerAddressCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginOpen(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginOpen(callback, asyncState)
        End Function
        
        Private Function OnEndOpen(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndOpen(result)
            Return Nothing
        End Function
        
        Private Sub OnOpenCompleted(ByVal state As Object)
            If (Not (Me.OpenCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent OpenCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub OpenAsync()
            Me.OpenAsync(Nothing)
        End Sub
        
        Public Overloads Sub OpenAsync(ByVal userState As Object)
            If (Me.onBeginOpenDelegate Is Nothing) Then
                Me.onBeginOpenDelegate = AddressOf Me.OnBeginOpen
            End If
            If (Me.onEndOpenDelegate Is Nothing) Then
                Me.onEndOpenDelegate = AddressOf Me.OnEndOpen
            End If
            If (Me.onOpenCompletedDelegate Is Nothing) Then
                Me.onOpenCompletedDelegate = AddressOf Me.OnOpenCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginOpenDelegate, Nothing, Me.onEndOpenDelegate, Me.onOpenCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginClose(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginClose(callback, asyncState)
        End Function
        
        Private Function OnEndClose(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndClose(result)
            Return Nothing
        End Function
        
        Private Sub OnCloseCompleted(ByVal state As Object)
            If (Not (Me.CloseCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent CloseCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub CloseAsync()
            Me.CloseAsync(Nothing)
        End Sub
        
        Public Overloads Sub CloseAsync(ByVal userState As Object)
            If (Me.onBeginCloseDelegate Is Nothing) Then
                Me.onBeginCloseDelegate = AddressOf Me.OnBeginClose
            End If
            If (Me.onEndCloseDelegate Is Nothing) Then
                Me.onEndCloseDelegate = AddressOf Me.OnEndClose
            End If
            If (Me.onCloseCompletedDelegate Is Nothing) Then
                Me.onCloseCompletedDelegate = AddressOf Me.OnCloseCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginCloseDelegate, Nothing, Me.onEndCloseDelegate, Me.onCloseCompletedDelegate, userState)
        End Sub
        
        Protected Overrides Function CreateChannel() As SearchService.ISearchData
            Return New SearchDataClientChannel(Me)
        End Function
        
        Private Class SearchDataClientChannel
            Inherits ChannelBase(Of SearchService.ISearchData)
            Implements SearchService.ISearchData
            
            Public Sub New(ByVal client As System.ServiceModel.ClientBase(Of SearchService.ISearchData))
                MyBase.New(client)
            End Sub
            
            Public Function BeginGetSearchData(ByVal accountNumber As String, ByVal firstName As String, ByVal lastName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements SearchService.ISearchData.BeginGetSearchData
                Dim _args((3) - 1) As Object
                _args(0) = accountNumber
                _args(1) = firstName
                _args(2) = lastName
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("GetSearchData", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndGetSearchData(ByVal result As System.IAsyncResult) As System.Collections.ObjectModel.ObservableCollection(Of SearchService.ServiceSearchResults) Implements SearchService.ISearchData.EndGetSearchData
                Dim _args((0) - 1) As Object
                Dim _result As System.Collections.ObjectModel.ObservableCollection(Of SearchService.ServiceSearchResults) = CType(MyBase.EndInvoke("GetSearchData", _args, result),System.Collections.ObjectModel.ObservableCollection(Of SearchService.ServiceSearchResults))
                Return _result
            End Function
            
            Public Function BeginUpdateConsumer(ByVal item As SearchService.ServiceConsumer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements SearchService.ISearchData.BeginUpdateConsumer
                Dim _args((1) - 1) As Object
                _args(0) = item
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("UpdateConsumer", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Sub EndUpdateConsumer(ByVal result As System.IAsyncResult) Implements SearchService.ISearchData.EndUpdateConsumer
                Dim _args((0) - 1) As Object
                MyBase.EndInvoke("UpdateConsumer", _args, result)
            End Sub
            
            Public Function BeginUpdateConsumerAddress(ByVal item As SearchService.ServiceConsumerAdress, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements SearchService.ISearchData.BeginUpdateConsumerAddress
                Dim _args((1) - 1) As Object
                _args(0) = item
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("UpdateConsumerAddress", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Sub EndUpdateConsumerAddress(ByVal result As System.IAsyncResult) Implements SearchService.ISearchData.EndUpdateConsumerAddress
                Dim _args((0) - 1) As Object
                MyBase.EndInvoke("UpdateConsumerAddress", _args, result)
            End Sub
        End Class
    End Class
End Namespace
